### ISSUE TITLE
Got lot of errors after updating to v0.11.0

### ISSUE THREAD

**Issue by lucianomlima** [smartlook/smartlook-react-native-sdk#8]
<details>
<summary>RuntimeException: java.lang.reflect.InvocationTargetException</summary>
java.io.FileNotFoundException: /data/user/0/com.jusbrasil.onlineoffice/files/sessions/XNKRBXB06FZDGSG32J/session_setting/session_init_info.txt (Is a directory)
    at java.io.FileInputStream.open0(FileInputStream.java)
    at java.io.FileInputStream.open(FileInputStream.java:200)
    at java.io.FileInputStream.<init>(FileInputStream.java:150)
    at kotlin.io.FilesKt__FileReadWriteKt.readBytes(FileReadWrite.kt:63)
    at kotlin.io.FilesKt__FileReadWriteKt.readText(FileReadWrite.kt:101)
    at kotlin.io.FilesKt__FileReadWriteKt.readText$default(FileReadWrite.kt:101)
    at com.smartlook.sdk.smartlook.c.e.a(SourceFile:112)
    at com.smartlook.sdk.smartlook.c.e.a(SourceFile:122)
    at com.smartlook.sdk.smartlook.analytics.b.h(SourceFile:49)
    at com.smartlook.sdk.smartlook.analytics.b.<init>(SourceFile:35)
    at com.smartlook.sdk.smartlook.analytics.a.b(SourceFile:67)
    at com.smartlook.sdk.smartlook.analytics.a.b(SourceFile:61)
    at com.smartlook.sdk.smartlook.analytics.b.e(SourceFile:212)
    at com.smartlook.sdk.smartlook.analytics.b.c(SourceFile:200)
    at com.smartlook.sdk.smartlook.analytics.b.b(SourceFile:168)
    at com.smartlook.sdk.smartlook.analytics.b.i(SourceFile:129)
    at com.smartlook.sdk.smartlook.analytics.b.a(SourceFile:232)
    at com.smartlook.sdk.smartlook.analytics.a.a(SourceFile:114)
    at com.smartlook.sdk.smartlook.a.a.b.a(SourceFile:139)
    at com.smartlook.sdk.smartlook.a.a.b.a(SourceFile:13)
    at com.smartlook.sdk.smartlook.a.a.b$f.a(SourceFile:115)
    at com.smartlook.sdk.smartlook.a.a.b$f.a(SourceFile:109)
    at com.smartlook.sdk.smartlook.a.a.onResponse(SourceFile:17)
    at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:71)
    at android.os.Handler.handleCallback(Handler.java:790)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:164)
    at android.app.ActivityThread.main(ActivityThread.java:6626)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)
java.lang.reflect.InvocationTargetException: null
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:448)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)
</details>

```
  React Native Environment Info:
    System:
      OS: macOS 10.14.5
      CPU: x64 Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz
      Memory: 374.02 MB / 8.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
      Yarn: 1.17.3 - ~/.nvm/versions/node/v10.15.3/bin/yarn
      npm: 6.10.2 - ~/.nvm/versions/node/v10.15.3/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        Build Tools: 27.0.3, 28.0.3, 29.0.0
        API Levels: 25, 26, 27, 28
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5692245
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.6 => 16.8.6 
      react-native: 0.59.8 => 0.59.8 
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7
```

**Comment by lucianomlima** [comment]
Maybe related to https://github.com/smartlook/smartlook-android-sdk/issues/31

**Comment by adamblack** [comment]
Hi @lucianomlima ,

we just released new version. There is also fix of above mentioned issue. In case of any problems, feel free to create new issue.

**Comment by lucianomlima** [comment]
Thanks! Please, update changelog too!
